# Copyright (c) 2025 SAP SE
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

"""add hsm partition config

Revision ID: 3afe6ad4bc3d
Revises: 8c74e2d7f1ff
Create Date: 2025-06-20 15:01:20.598651

"""

# revision identifiers, used by Alembic.
revision = "3afe6ad4bc3d"
down_revision = "8c74e2d7f1ff"

from alembic import op
import sqlalchemy as sa

import barbican


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hsm_partition_configs",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("slot_id", sa.String(length=255), nullable=False),
        sa.Column("token_label", sa.String(length=255), nullable=False),
        sa.Column("partition_label", sa.String(length=255), nullable=False),
        sa.Column(
            "credentials", barbican.model.models.JsonBlob(), nullable=False
        ),
        sa.Column(
            "partition_metadata",
            barbican.model.models.JsonBlob(),
            nullable=True,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "slot_id",
            name="_hsm_partition_config_project_slot_uc",
        ),
    )
    op.create_index(
        op.f("ix_hsm_partition_configs_project_id"),
        "hsm_partition_configs",
        ["project_id"],
        unique=False,
    )
